## The first function makes a matrix that can cache its inverse. The second function computes 
## the inverse of the matrix, which had been generated by the first function. However it gets 
## the inverse from the cache (and does not recalculate) if the inverse had already been 
## calculated (in this case the inverse is in the cache).

## Creates a list of four functions, which set/get the value of the matrix and set/get the 
## value of the inverted matrix.

makeCacheMatrix <- function(x = matrix()) {
  
  m <- NULL                                 
  set <- function(y){
    x <<- y
    m <<- NULL
  }
  
  get <- function() x                       
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m                  
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)           
    
}


## Calcultes the inverse of the matrix, which had been created with makeCacheMatrix. If the 
## inverse matrix is already in the cache it takes it from the cache and does not recalculate.

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x' 
  
  
  m <- x$getinverse()
  if(!is.null(m)){                        
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}
